//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducPractVer2._00
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmusementParkEntities : DbContext
    {
        public AmusementParkEntities()
            : base("name=AmusementParkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attractions> Attractions { get; set; }
        public virtual DbSet<AttractionType> AttractionType { get; set; }
        public virtual DbSet<AuthorizationData> AuthorizationData { get; set; }
        public virtual DbSet<CashierRoles> CashierRoles { get; set; }
        public virtual DbSet<Cashiers> Cashiers { get; set; }
        public virtual DbSet<CashRegisterNumbers> CashRegisterNumbers { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<FearLevels> FearLevels { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
    }
}
