//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducPractVer2._00
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionType
    {
        public int attraction_type_id { get; set; }
        public string attraction_type_name { get; set; }
        public Nullable<int> attraction_id { get; set; }
    
        public virtual Attractions Attractions { get; set; }
    }
}
