//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducPractVer2._00
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationData
    {
        public int authorization_id { get; set; }
        public string logins { get; set; }
        public string passwords { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual CashierRoles CashierRoles { get; set; }
    }
}
